# Generated by Django 3.0.5 on 2020-04-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormsHCI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domanda',
            name='testoDomanda',
            field=models.TextField(),
        ),
    ]
