# Generated by Django 3.0.5 on 2020-04-29 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormsHCI', '0002_auto_20200428_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='SUSModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=400, verbose_name='Nome')),
                ('domanda01', models.TextField(verbose_name='I think that I would like to use this system frequently.')),
                ('risposta01', models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')])),
                ('domanda02', models.TextField(verbose_name='I found the system unnecessarily complex.')),
                ('risposta02', models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')])),
                ('domanda03', models.TextField(verbose_name='I thought the system was easy to use.')),
                ('risposta03', models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')])),
                ('domanda04', models.TextField(verbose_name='I think that I would need the support of a technical person to be able to use this system.')),
                ('risposta04', models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')])),
                ('domanda05', models.TextField(verbose_name='I found the various functions in this system were well integrated.')),
                ('risposta05', models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')])),
                ('domanda06', models.TextField(verbose_name='I thought there was too much inconsistency in this system.')),
                ('risposta06', models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')])),
                ('domanda07', models.TextField(verbose_name='I would imagine that most people would learn to use this system very quickly.')),
                ('risposta07', models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')])),
                ('domanda08', models.TextField(verbose_name='I found the system very cumbersome to use.')),
                ('risposta08', models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')])),
                ('domanda09', models.TextField(verbose_name='I felt very confident using the system.')),
                ('risposta09', models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')])),
                ('domanda10', models.TextField(verbose_name='I needed to learn a lot of things before I could get going with this system.')),
                ('risposta10', models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')])),
            ],
        ),
        migrations.AddField(
            model_name='domanda',
            name='risposta',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=0),
        ),
    ]
