# Generated by Django 3.0.5 on 2020-05-29 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FormsHCI', '0003_auto_20200429_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeForm', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Quesito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Risposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='SUSModel',
        ),
        migrations.RemoveField(
            model_name='domanda',
            name='risposta',
        ),
        migrations.AlterField(
            model_name='domanda',
            name='testoDomanda',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='RispostaBreve',
            fields=[
                ('risposta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='FormsHCI.Risposta')),
            ],
            bases=('FormsHCI.risposta',),
        ),
        migrations.CreateModel(
            name='RispostaCheckbox',
            fields=[
                ('risposta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='FormsHCI.Risposta')),
            ],
            bases=('FormsHCI.risposta',),
        ),
        migrations.CreateModel(
            name='RispostaDataOra',
            fields=[
                ('risposta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='FormsHCI.Risposta')),
            ],
            bases=('FormsHCI.risposta',),
        ),
        migrations.CreateModel(
            name='RispostaElenco',
            fields=[
                ('risposta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='FormsHCI.Risposta')),
            ],
            bases=('FormsHCI.risposta',),
        ),
        migrations.CreateModel(
            name='RispostaMultipla',
            fields=[
                ('risposta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='FormsHCI.Risposta')),
            ],
            bases=('FormsHCI.risposta',),
        ),
        migrations.CreateModel(
            name='RispostaParagrafo',
            fields=[
                ('risposta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='FormsHCI.Risposta')),
            ],
            bases=('FormsHCI.risposta',),
        ),
        migrations.CreateModel(
            name='RispostaUpload',
            fields=[
                ('risposta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='FormsHCI.Risposta')),
            ],
            bases=('FormsHCI.risposta',),
        ),
        migrations.AddField(
            model_name='quesito',
            name='testoQuesito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FormsHCI.Domanda'),
        ),
        migrations.AddField(
            model_name='form',
            name='quesito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FormsHCI.Quesito'),
        ),
        migrations.AddField(
            model_name='quesito',
            name='risposta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FormsHCI.RispostaUpload'),
        ),
    ]
